### ISSUE TITLE
unable to pip  install

### ISSUE THREAD

**Issue by zahs123** [dominance-analysis/dominance-analysis#21]
**Describe the bug**
cannot pip install this as i get error

**To Reproduce**
1. pip install dominance-analysis

**Expected behavior**
it just works

**Additional context**
i am using windows, and use anaconda. 

and installed scipy using 'conda install scipy' 

result below:
```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zahra\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zahra\\AppData\\Local\\Temp\\pip-install-la_s4ox1\\scipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\zahra\\AppData\\Local\\Temp\\pip-install-la_s4ox1\\scipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zahra\AppData\Local\Temp\pip-record-xtwrjrzn\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\zahra\anaconda3\Include\scipy'
         cwd: C:\Users\zahra\AppData\Local\Temp\pip-install-la_s4ox1\scipy\
    Complete output (131 lines):

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    Running from scipy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:/Users/zahra/anaconda3\\Library\\lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\zahra\\anaconda3\\lib', 'C:\\', 'C:\\Users\\zahra\\anaconda3\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['C:\\Users\\zahra\\anaconda3\\lib', 'C:\\', 'C:\\Users\\zahra\\anaconda3\\libs']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['C:\\Users\\zahra\\anaconda3\\lib', 'C:\\', 'C:\\Users\\zahra\\anaconda3\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\lib
      libraries tatlas,tatlas not found in C:\Users\zahra\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\libs
      libraries tatlas,tatlas not found in C:\Users\zahra\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\lib
      libraries satlas,satlas not found in C:\Users\zahra\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\libs
      libraries satlas,satlas not found in C:\Users\zahra\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\zahra\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\libs
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\zahra\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\lib
      libraries f77blas,cblas,atlas not found in C:\Users\zahra\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\Users\zahra\anaconda3\libs
      libraries f77blas,cblas,atlas not found in C:\Users\zahra\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['C:\\Users\\zahra\\anaconda3\\lib', 'C:\\', 'C:\\Users\\zahra\\anaconda3\\libs']
      NOT AVAILABLE

    C:\Users\zahra\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    C:\Users\zahra\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zahra\AppData\Local\Temp\pip-install-la_s4ox1\scipy\setup.py", line 492, in <module>
        setup_package()
      File "C:\Users\zahra\AppData\Local\Temp\pip-install-la_s4ox1\scipy\setup.py", line 488, in setup_package
        setup(**metadata)
      File "C:\Users\zahra\anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\zahra\AppData\Local\Temp\pip-install-la_s4ox1\scipy\setup.py", line 395, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.

```

**Comment by Robin0105** [comment]
Having the same challenge

**Comment by bhagatsajan0073** [comment]
Hi @zahs123 @Robin0105,

Please try dominance-analysis in a separate Conda environment with the following version of NumPy and Scipy 

Numpy : numpy==1.20.1
Scipy : scipy==1.5.0

let me know if this solves your issue

**Comment by u01ai11** [comment]
Thanks for this super helpful package! 

I have this same issue on macOS. Since the Big Sur update it's been pretty much impossible to install Scipy 1.5.0 on the operating system, see: https://github.com/scipy/scipy/issues/13102. 

So perhaps you could remove the Scipy==1.5.0 from the setup.py? because at the moment anybody who is using a reasonably up-to-date Python distribution on a newer macOS will run into this problem. 

In the end I got round this by installing from the old .whl file in this repo. But I'm sure this is out of date? 

I downloaded the file from https://github.com/dominance-analysis/dominance-analysis/blob/master/dominance_analysis/dist/dominance_analysis-1.0.0-py3-none-any.whl

and ran:
`pip install dominance_analysis-1.0.0-py3-none-any.whl`

**Comment by sajanbhagat** [comment]
> @sajanbhagat kindly look into pip installation with latest python versions, it does not work. I could only make it work with the whl file here (https://github.com/dominance-analysis/dominance-analysis/blob/master/dominance_analysis/dist/dominance_analysis-1.0.0-py3-none-any.whl), but it is outdated. Thank you

Could you please help me with the python version you are trying?
We will try to test it on the latest python version and solve the dependencies issues, meanwhile please proceed with .whl file

**Comment by sajanbhagat** [comment]
> > @sajanbhagat kindly look into pip installation with latest python versions, it does not work. I could only make it work with the whl file here (https://github.com/dominance-analysis/dominance-analysis/blob/master/dominance_analysis/dist/dominance_analysis-1.0.0-py3-none-any.whl), but it is outdated. Thank you
> 
> Could you please help me with the python version you are trying? We will try to test it on the latest python version and solve the dependencies issues, meanwhile please proceed with .whl file

Currently, we are able to support dominance-analysis only on Python 3.8 and below because of underlying dependency on Scipy=1.5.0 which further is supported only till Python 3.8. I have tested dominance analysis via Pip Install in Virtual Env and it works fine for me without any issues. 

Still, If you face any challenges on Python 3.8 and below, please feel free to raise an issue.

Thanks 
Sajan

**Comment by timbo112711** [comment]
@sajanbhagat, is there any current plan for supporting this awesome package above `Python 3.8`? Would love to use this package in our web app but unfortunately we are running `Python 3.9` and can't downgrade the version.
